name: Check Free Games

on:
  schedule:
    - cron: "55 0 * * *"
  workflow_dispatch:

jobs:
  check-free-games:
    runs-on: ubuntu-latest

    steps:
      - name: Call free games checker endpoint
        run: |
          curl --fail -X GET "${{ secrets.APP_URL }}/api/jobs/check-free-games" \
            -H "Authorization: Bearer ${{ secrets.CHECK_PRICES_SECRET }}"